[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/letsencrypt/live/agilizapro.cloud/fullchain.pem"
      keyFile = "/letsencrypt/live/agilizapro.cloud/privkey.pem"